/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AppApiCardCardListParams,
  PagedCardListSchemaOut
} from '.././entities';

import { customInstance } from '../../axios-instance';
import type { ErrorType } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Card List
 */
export const appApiCardCardList = (
    params?: AppApiCardCardListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedCardListSchemaOut>(
      {url: `/api/v1/card/list`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getAppApiCardCardListQueryKey = (params?: AppApiCardCardListParams,) => {
    return [`/api/v1/card/list`, ...(params ? [params]: [])] as const;
    }

    
export const getAppApiCardCardListQueryOptions = <TData = Awaited<ReturnType<typeof appApiCardCardList>>, TError = ErrorType<unknown>>(params?: AppApiCardCardListParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appApiCardCardList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppApiCardCardListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appApiCardCardList>>> = ({ signal }) => appApiCardCardList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: 10000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appApiCardCardList>>, TError, TData> & { queryKey: QueryKey }
}

export type AppApiCardCardListQueryResult = NonNullable<Awaited<ReturnType<typeof appApiCardCardList>>>
export type AppApiCardCardListQueryError = ErrorType<unknown>


/**
 * @summary Card List
 */

export function useAppApiCardCardList<TData = Awaited<ReturnType<typeof appApiCardCardList>>, TError = ErrorType<unknown>>(
 params?: AppApiCardCardListParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appApiCardCardList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppApiCardCardListQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getAppApiCardCardListSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof appApiCardCardList>>, TError = ErrorType<unknown>>(params?: AppApiCardCardListParams, options?: { query?:UseSuspenseQueryOptions<Awaited<ReturnType<typeof appApiCardCardList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppApiCardCardListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appApiCardCardList>>> = ({ signal }) => appApiCardCardList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: 10000,  ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof appApiCardCardList>>, TError, TData> & { queryKey: QueryKey }
}

export type AppApiCardCardListSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof appApiCardCardList>>>
export type AppApiCardCardListSuspenseQueryError = ErrorType<unknown>


/**
 * @summary Card List
 */

export function useAppApiCardCardListSuspense<TData = Awaited<ReturnType<typeof appApiCardCardList>>, TError = ErrorType<unknown>>(
 params?: AppApiCardCardListParams, options?: { query?:UseSuspenseQueryOptions<Awaited<ReturnType<typeof appApiCardCardList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppApiCardCardListSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



