/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */
import type { AccountFilterSchemaType } from './accountFilterSchemaType';

export interface AccountFilterSchema {
  type?: AccountFilterSchemaType;
}
