/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */
import type { AccountListSchemaOutCode } from './accountListSchemaOutCode';

export interface AccountListSchemaOut {
  id: number;
  name: string;
  type: string;
  code: AccountListSchemaOutCode;
  is_system: boolean;
  children: AccountListSchemaOut[];
}
