/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */
import type { CardListSchemaOutBalance } from './cardListSchemaOutBalance';

export interface CardListSchemaOut {
  id: number;
  name: string;
  balance: CardListSchemaOutBalance;
  last_date: string;
}
