/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */

export interface Input {
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
}
