/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */
import type { TransactionListSchema } from './transactionListSchema';

export interface PagedTransactionListSchema {
  items: TransactionListSchema[];
  count: number;
}
