/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */
import type { ReportListSchemaOutTotal } from './reportListSchemaOutTotal';

export interface ReportListSchemaOut {
  account_id: number;
  account_name: string;
  total: ReportListSchemaOutTotal;
}
