/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */
import type { TransactionListSchemaAmount } from './transactionListSchemaAmount';
import type { AccountSchemaOut } from './accountSchemaOut';
import type { CardSchemaOut } from './cardSchemaOut';

export interface TransactionListSchema {
  id: number;
  name: string;
  amount: TransactionListSchemaAmount;
  date: string;
  account: AccountSchemaOut;
  card: CardSchemaOut;
}
