/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * My Expenses
 * OpenAPI spec version: 1.0
 */

export interface UpdateCategoryTransactionSchema {
  transaction_id: number;
  account_id: number;
}
